data-directory: 'glucose.json'
conditions_directory: '../10k_synthea_covid19_csv/conditions.csv'
patients_directory: '../10k_synthea_covid19_csv/patients.csv'
observations_directory: '../10k_synthea_covid19_csv/observations.csv'
careplans_directory: '../10k_synthea_covid19_csv/careplans.csv'
encounters_directory: '../10k_synthea_covid19_csv/encounters.csv'
seasonal_effect: '../assessments/KNMI_20181231.txt.tsv'
Total_death: 'Total_death.csv'
couse_of_death: 'cause_of_death.csv'
lifestyle: 'occurrence_of_infectious_disease.csv'
